apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: lentera-id-tls
spec:
  secretName: lentera-id
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: lentera.id
  dnsNames:
    - lentera.id
    - www.lentera.id
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - lentera.id
          - www.lentera.id